# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpersonal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='district',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='division',
            field=models.CharField(choices=[('Barisal', 'Barisal'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Mymensingh', 'Mymensingh'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], default='Dhaka', max_length=45),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='guests',
            field=models.CharField(choices=[('0', 'NONE'), ('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='kids',
            field=models.CharField(choices=[('0', 'NONE'), ('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='mate',
            field=models.CharField(choices=[('0', 'NONE'), ('1', '01')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='mobilenumber',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='others',
            field=models.CharField(choices=[('0', 'NONE'), ('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='spous',
            field=models.CharField(choices=[('0', 'NONE'), ('1', '01')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationaddress',
            name='thana',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='method',
            field=models.CharField(choices=[('None', 'NONE'), ('Cash', 'CASH'), ('Bank', 'BANK'), ('BKash', 'BKASH'), ('Others', 'OTHERS')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='mobilenumber',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Processing', 'PROCESSING'), ('Paid', 'PAID'), ('Unpaid', 'UNPAID')], default='Unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A +ve'), ('B+', 'B +ve'), ('O+', 'O +ve'), ('AB+', 'AB +ve'), ('A-', 'A -ve'), ('B-', 'B -ve'), ('O-', 'O -ve'), ('AB-', 'AB -ve')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], default='Male', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='kids',
            field=models.CharField(blank=True, choices=[('0', 'NONE'), ('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05')], default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='mobilenumber',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='organization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registrationpersonal',
            name='spousname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
